### PR TITLE
Extract package and fix typo (fixes #1)

### LINKED ISSUE #1: Unable to use as a package/library
Hi Nisha,

I'm unable to use this code at present as a package or library, so I'd like to send you a quick PR that enables this. I'll then make use of this as a serverless function as we've discussed before which I think will be fun 😄

I've also seen a *typo in the README and a couple of Go linting issues in the comments which I'll fix too.

Alex

### PR DESCRIPTION
**Pull request by alexellis**
- extracted pkg so that the code can be used as a library
- corrected typo in README
- corrected Golang comments - comments on structs should start
with the name of the struct (VSCode shows these hints)

Tested locally on MacOS

Signed-off-by: Alex Ellis <alexellis2@gmail.com>

### CODE REVIEW

**Comment by nishakm** [comment]
Thank you!! Your PR taught me some more Go!

**Comment by alexellis** [comment]
No problems :-) glad you could merge it easily. It's also now live on the function store of OpenFaaS!

**Comment by nishakm** [comment]
Way cool! I am interested in knowing how the OpenFaaS function calls the Generate function from this repo: https://github.com/openfaas/store/commit/4fc208b3741669a7d2422da5781c2e85a1f0657a
For more Go Learning :)

**Comment by alexellis** [comment]
Sure, the handler is here - https://github.com/openfaas/faas/tree/master/sample-functions/business-strategy-generator and the stack.yml file is one level up in the tree. To try it, follow the instructions in Lab 1/2 of the workshop and then deploy from Function Store.

**Pull request merged**
